
networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    build:  
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "4411:4411"
    env_file:
      - ./backend/.env
    networks:
      - dev

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    networks:
      - dev
   
