networks:
 noper:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf 
    depends_on:
      - backend
      - frontend
    networks:
      - noper

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - noper

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - noper
