networks:
  noper:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - noper

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
    expose:
      - "4411"  # Открыт для взаимодействия между контейнерами
    networks:
      - noper
    env_file:
      - ./backend/.env 

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "80"  # Открыт для взаимодействия с Nginx
    networks:
      - noper
    env_file:
      - ./frontend/.env 