networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    # volumes:
    #   - ./nginx.conf:/etc/nginx/nginx.conf
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf    # Подключаем nginx конфиг
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    build:  
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    networks:
      - dev

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
    - ./frontend/dist:/usr/share/nginx/html
    env_file:
      - ./frontend/.env
    networks:
      - dev
   
